//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Extensions.MouseServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MouseServiceReference.IMouseService")]
    public interface IMouseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/StartListening", ReplyAction="http://tempuri.org/IMouseService/StartListeningResponse")]
        void StartListening();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/StartListening", ReplyAction="http://tempuri.org/IMouseService/StartListeningResponse")]
        System.Threading.Tasks.Task StartListeningAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/StopListening", ReplyAction="http://tempuri.org/IMouseService/StopListeningResponse")]
        void StopListening();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/StopListening", ReplyAction="http://tempuri.org/IMouseService/StopListeningResponse")]
        System.Threading.Tasks.Task StopListeningAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/GetMousePosition", ReplyAction="http://tempuri.org/IMouseService/GetMousePositionResponse")]
        Extensions.Models.Mouse.Win32.Point GetMousePosition();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/GetMousePosition", ReplyAction="http://tempuri.org/IMouseService/GetMousePositionResponse")]
        System.Threading.Tasks.Task<Extensions.Models.Mouse.Win32.Point> GetMousePositionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseLeftDown", ReplyAction="http://tempuri.org/IMouseService/MouseLeftDownResponse")]
        void MouseLeftDown();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseLeftDown", ReplyAction="http://tempuri.org/IMouseService/MouseLeftDownResponse")]
        System.Threading.Tasks.Task MouseLeftDownAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseLeftUp", ReplyAction="http://tempuri.org/IMouseService/MouseLeftUpResponse")]
        void MouseLeftUp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseLeftUp", ReplyAction="http://tempuri.org/IMouseService/MouseLeftUpResponse")]
        System.Threading.Tasks.Task MouseLeftUpAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseLeftClick", ReplyAction="http://tempuri.org/IMouseService/MouseLeftClickResponse")]
        void MouseLeftClick();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseLeftClick", ReplyAction="http://tempuri.org/IMouseService/MouseLeftClickResponse")]
        System.Threading.Tasks.Task MouseLeftClickAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseRightDown", ReplyAction="http://tempuri.org/IMouseService/MouseRightDownResponse")]
        void MouseRightDown();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseRightDown", ReplyAction="http://tempuri.org/IMouseService/MouseRightDownResponse")]
        System.Threading.Tasks.Task MouseRightDownAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseRightUp", ReplyAction="http://tempuri.org/IMouseService/MouseRightUpResponse")]
        void MouseRightUp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseRightUp", ReplyAction="http://tempuri.org/IMouseService/MouseRightUpResponse")]
        System.Threading.Tasks.Task MouseRightUpAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseRightClick", ReplyAction="http://tempuri.org/IMouseService/MouseRightClickResponse")]
        void MouseRightClick();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseRightClick", ReplyAction="http://tempuri.org/IMouseService/MouseRightClickResponse")]
        System.Threading.Tasks.Task MouseRightClickAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseMiddleUp", ReplyAction="http://tempuri.org/IMouseService/MouseMiddleUpResponse")]
        void MouseMiddleUp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseMiddleUp", ReplyAction="http://tempuri.org/IMouseService/MouseMiddleUpResponse")]
        System.Threading.Tasks.Task MouseMiddleUpAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseMiddleDown", ReplyAction="http://tempuri.org/IMouseService/MouseMiddleDownResponse")]
        void MouseMiddleDown();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseMiddleDown", ReplyAction="http://tempuri.org/IMouseService/MouseMiddleDownResponse")]
        System.Threading.Tasks.Task MouseMiddleDownAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseMiddleClick", ReplyAction="http://tempuri.org/IMouseService/MouseMiddleClickResponse")]
        void MouseMiddleClick();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseMiddleClick", ReplyAction="http://tempuri.org/IMouseService/MouseMiddleClickResponse")]
        System.Threading.Tasks.Task MouseMiddleClickAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseWheel", ReplyAction="http://tempuri.org/IMouseService/MouseWheelResponse")]
        void MouseWheel(int delta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/MouseWheel", ReplyAction="http://tempuri.org/IMouseService/MouseWheelResponse")]
        System.Threading.Tasks.Task MouseWheelAsync(int delta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/KeyUp", ReplyAction="http://tempuri.org/IMouseService/KeyUpResponse")]
        void KeyUp(System.Windows.Forms.Keys key, bool ctrl, bool win, bool alt, bool shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/KeyUp", ReplyAction="http://tempuri.org/IMouseService/KeyUpResponse")]
        System.Threading.Tasks.Task KeyUpAsync(System.Windows.Forms.Keys key, bool ctrl, bool win, bool alt, bool shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/GetPCName", ReplyAction="http://tempuri.org/IMouseService/GetPCNameResponse")]
        string GetPCName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/GetPCName", ReplyAction="http://tempuri.org/IMouseService/GetPCNameResponse")]
        System.Threading.Tasks.Task<string> GetPCNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/PushWhoIAm", ReplyAction="http://tempuri.org/IMouseService/PushWhoIAmResponse")]
        void PushWhoIAm(string pcName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMouseService/PushWhoIAm", ReplyAction="http://tempuri.org/IMouseService/PushWhoIAmResponse")]
        System.Threading.Tasks.Task PushWhoIAmAsync(string pcName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMouseServiceChannel : Test_Extensions.MouseServiceReference.IMouseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MouseServiceClient : System.ServiceModel.ClientBase<Test_Extensions.MouseServiceReference.IMouseService>, Test_Extensions.MouseServiceReference.IMouseService {
        
        public MouseServiceClient() {
        }
        
        public MouseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MouseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MouseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MouseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartListening() {
            base.Channel.StartListening();
        }
        
        public System.Threading.Tasks.Task StartListeningAsync() {
            return base.Channel.StartListeningAsync();
        }
        
        public void StopListening() {
            base.Channel.StopListening();
        }
        
        public System.Threading.Tasks.Task StopListeningAsync() {
            return base.Channel.StopListeningAsync();
        }
        
        public Extensions.Models.Mouse.Win32.Point GetMousePosition() {
            return base.Channel.GetMousePosition();
        }
        
        public System.Threading.Tasks.Task<Extensions.Models.Mouse.Win32.Point> GetMousePositionAsync() {
            return base.Channel.GetMousePositionAsync();
        }
        
        public void MouseLeftDown() {
            base.Channel.MouseLeftDown();
        }
        
        public System.Threading.Tasks.Task MouseLeftDownAsync() {
            return base.Channel.MouseLeftDownAsync();
        }
        
        public void MouseLeftUp() {
            base.Channel.MouseLeftUp();
        }
        
        public System.Threading.Tasks.Task MouseLeftUpAsync() {
            return base.Channel.MouseLeftUpAsync();
        }
        
        public void MouseLeftClick() {
            base.Channel.MouseLeftClick();
        }
        
        public System.Threading.Tasks.Task MouseLeftClickAsync() {
            return base.Channel.MouseLeftClickAsync();
        }
        
        public void MouseRightDown() {
            base.Channel.MouseRightDown();
        }
        
        public System.Threading.Tasks.Task MouseRightDownAsync() {
            return base.Channel.MouseRightDownAsync();
        }
        
        public void MouseRightUp() {
            base.Channel.MouseRightUp();
        }
        
        public System.Threading.Tasks.Task MouseRightUpAsync() {
            return base.Channel.MouseRightUpAsync();
        }
        
        public void MouseRightClick() {
            base.Channel.MouseRightClick();
        }
        
        public System.Threading.Tasks.Task MouseRightClickAsync() {
            return base.Channel.MouseRightClickAsync();
        }
        
        public void MouseMiddleUp() {
            base.Channel.MouseMiddleUp();
        }
        
        public System.Threading.Tasks.Task MouseMiddleUpAsync() {
            return base.Channel.MouseMiddleUpAsync();
        }
        
        public void MouseMiddleDown() {
            base.Channel.MouseMiddleDown();
        }
        
        public System.Threading.Tasks.Task MouseMiddleDownAsync() {
            return base.Channel.MouseMiddleDownAsync();
        }
        
        public void MouseMiddleClick() {
            base.Channel.MouseMiddleClick();
        }
        
        public System.Threading.Tasks.Task MouseMiddleClickAsync() {
            return base.Channel.MouseMiddleClickAsync();
        }
        
        public void MouseWheel(int delta) {
            base.Channel.MouseWheel(delta);
        }
        
        public System.Threading.Tasks.Task MouseWheelAsync(int delta) {
            return base.Channel.MouseWheelAsync(delta);
        }
        
        public void KeyUp(System.Windows.Forms.Keys key, bool ctrl, bool win, bool alt, bool shift) {
            base.Channel.KeyUp(key, ctrl, win, alt, shift);
        }
        
        public System.Threading.Tasks.Task KeyUpAsync(System.Windows.Forms.Keys key, bool ctrl, bool win, bool alt, bool shift) {
            return base.Channel.KeyUpAsync(key, ctrl, win, alt, shift);
        }
        
        public string GetPCName() {
            return base.Channel.GetPCName();
        }
        
        public System.Threading.Tasks.Task<string> GetPCNameAsync() {
            return base.Channel.GetPCNameAsync();
        }
        
        public void PushWhoIAm(string pcName) {
            base.Channel.PushWhoIAm(pcName);
        }
        
        public System.Threading.Tasks.Task PushWhoIAmAsync(string pcName) {
            return base.Channel.PushWhoIAmAsync(pcName);
        }
    }
}
